index:
    pattern:    /
    defaults: { _controller: LOMUserBundle:Default:index }

LOMUserBundle_admin_role:
        resource: "@LOMUserBundle/Resources/config/routing/role.yml"
        prefix:   /admin/role

LOMUserBundle_admin_user:
        resource: "@LOMUserBundle/Resources/config/routing/user.yml"
        prefix:   /admin/user

LOMUserBundle_admin:
    path: /admin
    defaults: { _controller: LOMUserBundle:Admin:index }
