LOMUserBundle_admin_role:
        resource: "@LOMUserBundle/Resources/config/routing/admin_role.yml"
        prefix:   /admin/role

LOMUserBundle_admin_user:
        resource: "@LOMUserBundle/Resources/config/routing/admin_user.yml"
        prefix:   /admin/user

LOMUserBundle_admin:
    path: /admin
    defaults: { _controller: LOMUserBundle:Admin:index }

LOMUserBundle_user:
        resource: "@LOMUserBundle/Resources/config/routing/user.yml"
        prefix:   /user
