parameters:
#    lom_user.example.class: LOM\UserBundle\Example

services:
#    lom_user.example:
#        class: %lom_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
