parameters:
#    lom_pln.example.class: LOM\PlnBundle\Example

services:
    lom.twig.lom_classidextension:
        class: LOM\PlnBundle\Twig\ClassIdExtension
        tags:
            - { name: twig.extension }
#    lom_pln.example:
#        class: %lom_pln.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
