<?php

namespace LOM\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

//    from
//	lom_users inner join user_role
//		on lom_users.id = user_id
//	inner join lom_roles
//		on role_id = lom_roles.id;
    public function loadUserByUsername($username) {
        $q = $this->createQueryBuilder('u, r')
                ->where('u.username = :username')
                ->leftJoin('u.roles', 'r')
                ->setParameter('username', $username)
                ->getQuery();
        $user = null;
        try {
            $user = $q->getSingleResult();
        } catch (Exception $ex) {
            $message = sprintf(
                    'Unable to find an active user identified by "%s".', $username
            );
            throw new UsernameNotFoundException($message, 0, $ex);
        }
        return $user;
    }

    public function refreshUser(UserInterface $user) {
        $class = get_class($user);
        if (!$this->supportsClass($class)) {
            throw new UnsupportedUserException(sprintf('Instances of "%s" are not supported.', $class));
        }
        return $this->find($user->getId());
    }

    public function supportsClass($class) {
        return $this->getEntityName() === $class || is_subclass_of($class, $this->getEntityName());
    }

}
