lom_user:
    resource: "@LOMUserBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults: { _controller: LOMUserBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout

password_lost:
    path: /reset
    defaults: { _controller: LOMUserBundle:Security:lostPassword }

password_send:
    path: /reset/send
    defaults: { _controller: LOMUserBundle:Security:sendPassword }

password_confirm:
    path: /reset/confirm
    defaults: { _controller: LOMUserBundle:Security:confirmPassword }

password_changed:
    path: /reset/changed
    defaults: { _controller: LOMUserBundle:Security:changedPassword }