lom_user:
    resource: "@LOMUserBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults: { _controller: LOMUserBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout

login_reset:
    path: /reset
    defaults: { _controller: LOMUserBundle:Security:lostPassword }

login_send:
    path: /reset/send
    defaults: { _controller: LOMUserBundle:Security:sendPassword }