security:
    encoders:
        LOM\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        main:
            entity:
                class: LOMUserBundle:User
                property: username
                
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern: ^/login$
            anonymous: ~

        reset_firewall:
            pattern: ^/reset
            anonymous: ~

        lom_users:
            remember_me:
                key: "%secret%"
                lifetime: 3153600
                path: /
                domain: ~
                
            pattern:    ^/
            form_login:
                login_path: login
                check_path: login_check
                csrf_provider: form.csrf_provider
                default_target_path: user
                
            logout:
                path: /logout
                target: /
                
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_USER }
        