security:
    encoders:
        LOM\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class: LOMUserBundle:User
                property: username
                
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        demo_login:
            pattern:  ^/demo/secured/login$
            security: false

        demo_secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _demo_security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

        login_firewall:
            pattern: ^/login$
            anonymous: ~

        reset_firewall:
            pattern: ^/reset
            anonymous: ~

        lom_users:
            pattern:    ^/
            form_login:
                login_path: login
                check_path: login_check
                csrf_provider: form.csrf_provider
            logout:
                path: /logout
                target: /
                
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_USER }
        