user:
    path:     /
    defaults: { _controller: "LOMUserBundle:User:index" }

user_edit:
    path:     /edit
    defaults: { _controller: "LOMUserBundle:User:edit" }

user_update:
    path:     /update
    defaults: { _controller: "LOMUserBundle:User:update" }
    requirements: { _method: post|put }

user_password:
    path: /password
    defaults: { _controller: "LOMUserBundle:User:password" }

user_password_update:
    path: /password/update
    defaults: { _controller: "LOMUserBundle:User:passwordUpdate" }
